<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Shri-PC" failures="1" tests="6" name="Test" time="0.145" errors="0" timestamp="2021-08-14T14:40:28 IST">
  <testcase classname="com.javabykiran.LoginTestCases" name="checkTestOne" time="0.022">
    <failure type="java.lang.AssertionError" message="expected [5] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [2]
at com.javabykiran.LoginTestCases.checkTestOne(LoginTestCases.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- checkTestOne -->
  <testcase classname="com.javabykiran.LoginTestCases" name="checkTestThree" time="0.012"/>
  <testcase classname="com.javabykiran.LoginTestCases" name="checkTestTwo" time="0.004"/>
  <testcase classname="com.javabykiran.SignupTestcases" name="checkTestOne" time="0.003"/>
  <testcase classname="com.javabykiran.SignupTestcases" name="checkTestThree" time="0.001"/>
  <testcase classname="com.javabykiran.SignupTestcases" name="checkTestTwo" time="0.001"/>
</testsuite> <!-- Test -->
